[package]
name = "hello-world-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
octabot-rust-sdk = { path = "../.." }

[package.metadata.component]
package = "example:hello-world"
