[package]
name = "keyvalue-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
octabot-rust-sdk = { path = "../.." }
log = "0.4.25"

[package.metadata.component]
package = "example:keyvalue"
