name: Release
on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+"
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  TARGET_DIR: target_ci

jobs:
  crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish octabot-rust-sdk to crates.io
        working-directory: ./
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
